name: Publish Release

on: 
  push:
    tags:
      - "v*"

jobs:
  export:
    runs-on: ubuntu-latest
    permissions: write-all
    name: Export Game
    steps:
    - name: checkout
      uses: actions/checkout@v4
    
    - name: godot-export
      id: export
      uses: firebelley/godot-export@v5.2.1
      with:
        godot_executable_download_url: https://github.com/godotengine/godot-builds/releases/download/4.2.1-stable/Godot_v4.2.1-stable_mono_linux_x86_64.zip
        godot_export_templates_download_url: https://github.com/godotengine/godot-builds/releases/download/4.2.1-stable/Godot_v4.2.1-stable_mono_export_templates.tpz
        relative_project_path: ./game
        archive_output: true
    
    - name: release
      uses: ncipollo/release-action@v1
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        generateReleaseNotes: true
        tag: ${{github.ref_name}}
        artifacts: ${{steps.export.outputs.archive_directory}}/*
